theme: jekyll-theme-cayman
github:
  is_project_page: false
title: Research Methods for Political Science A and B
description: Repository with teaching material for the tutorials of the module Research Methods for Political Science (PO3110 & PO3111)
